### ISSUE TITLE
Homepage Featured Products: It stated in the project scope that the items to be display are "Featured" products. It should need a featured option.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Superoo-Falcon-Spares#26]
![image](https://cloud.githubusercontent.com/assets/12888048/13520527/01db93ae-e21c-11e5-8332-dec242340de8.png)

![image](https://cloud.githubusercontent.com/assets/12888048/13520558/4e5c8abc-e21c-11e5-963d-4be769898bb2.png)

**Comment by asif-titan** [comment]
please check the screenshot below we do not need to create an additional field, but just check the star field if we want it to be featured product.

![superoo falcon spares featured](https://cloud.githubusercontent.com/assets/13450796/13944511/d7708368-f02b-11e5-9f8c-0bfc002b780c.png)
