### ISSUE TITLE
Contact us page : Commas should be implemented for address field

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Superoo-Falcon-Spares#66]
![contact us - superoo falcon spares 2016-03-16 15-09-40](https://cloud.githubusercontent.com/assets/13309806/13809153/587cf244-eb8f-11e5-8c1a-d36f5c8762b5.png)

**Comment by asif-titan** [comment]
As per the design there are no commas.

**Comment by romatitan** [comment]
commas are added
