### ISSUE TITLE
Testimonials page : Title should not cater more than 2 lines

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Superoo-Falcon-Spares#70]
![testimonials2](https://cloud.githubusercontent.com/assets/13309806/13809298/17f12370-eb90-11e5-8309-d3f5c1df1757.png)

**Comment by asif-titan** [comment]
As there is no single page we will have to show the full title and content on this page itself, it cannot be restricted to just two lines as it will seem incomplete to the user.
